baseURL = "https://ridetrek.netlify.app/"
title = "Ridetrek Adventure"
pagerSize = 5
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
ShowPostThumbnail = true
ShowPostCover = true
extendHead = true
customHead = "partials/extend_head.html"
customCSS = ["css/custom.css"]
env = "production"
title = "Ridetrek Adventure"
description = "A blog for Adventure Rider"
keywords = [ "Blog", "Adventure", "Rider" ]
author = "laodesidik"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = false
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = false
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

  [params.assets]
  disableFingerprinting = true
  favicon = "<link / abs url>"
  favicon16x16 = "<link / abs url>"
  favicon32x32 = "<link / abs url>"
  apple_touch_icon = "<link / abs url>"
  safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "Home"
  icon = "/apple-touch-icon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = true
  title = "Ridetrek Adventure"
  subtitle = "Laode Sidik"
  imageUrl = "/images/laodesidik.webp"
  imageWidth = 140
  imageHeight = 140
  imageTitle = "laodesidik"

    [[params.profileMode.buttons]]
    name = "Blog"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "My Ride"
    url = "dashboard"

  [params.homeInfoParams]
  Title = "Hi there 👋"
  Content = "Welcome to my blog"

  [[params.socialIcons]]
  name = "instagram"
  url = "https://instagram.com/sipapadjohan/"

  [[params.socialIcons]]
  name = "facebook"
  url = "https://facebook.com/retrodalems"

  [[params.socialIcons]]
  name = "whatsapp"
  url = "https://wa.me/628113636123?text=Halo%20om%20Laode%21%20"

  [[params.socialIcons]]
  name = "youtube"
  url = "#"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = false
  hiddenInList = false
  hiddenInSingle = false

  [params.editPost]
  URL = "https://github.com/<path_to_repo>/content"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  limit = 10
  keys = [ "title", "permalink", "summary", "content" ]

[menu]
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "dashboard"
name = "Progress Touring"
url = "/dashboard/"
weight = 10

[[menu.main]]
identifier = "octanebooster"
name = "Hitung Octane Booster"
url = "/octanebooster/"
weight = 10


[markup.highlight]
noClasses = false